### ISSUE TITLE
Blank page after npm run start

### ISSUE THREAD

**Issue by matteorizziWT** [Esri/water-balance-app#9]
Dear Jinnan Zhang,

First of all, many congratulations on your work. It is simply amazing as you can exploit all those data in the WaterBalance App. 

I was trying to run it on my Windows machine:

1. I Cloned the repo
2. I installed all the dependencies with `npm install.`
3. I run `npm run start`

I have no error while compiling (in fact, the log is empty), but unfortunately, when I open the browser on the http://localhost:8080/, I got only a blank page without any console errors.

![unknown](https://user-images.githubusercontent.com/75792655/109626323-b1709180-7b40-11eb-9f17-1b4734820892.png)

The problem seems to be in the loading of the content of the **root div** because, on my browser, it is empty and not populated as it is on your live demo.

![unknown2](https://user-images.githubusercontent.com/75792655/109626694-22b04480-7b41-11eb-8b6a-f0c89ed92fe9.png)

Do you have any idea how to fix this problem? 
Thank you in advance for your support.
 

Best regards,
Matteo

**Comment by vannizhang** [comment]
@matteorizziWT 

Hi Matteo, thanks for reporting this issue, it seems for some reason the `ReactDOM.render` function from [index.tsx](https://github.com/Esri/water-balance-app/blob/master/src/index.tsx#L10) didn't get called, that's why the root div is empty.
Did you happen to modify the [entry point](https://github.com/Esri/water-balance-app/blob/master/webpack.config.js#L14) in the webpack config file? Because modifying that can cause the issue that you described.

Jinnan

**Comment by matteorizziWT** [comment]
Yes exactly, that function is not called.
Unfortunately I didn't modify the entry point in the webpack config...

**Comment by vannizhang** [comment]
@matteorizziWT Could you please clone the repo and run the commands again? We updated the app to use new GLDAS Imagery Services couple months ago and I forgot to do a pull request to merge those changes from my fork to this Esri repo. 

Please let me know if that fixes the issue.

Jinnan

**Comment by matteorizziWT** [comment]
@vannizhang Thank you so much. Everything now is working fine.

**Comment by vannizhang** [comment]
@matteorizziWT You are welcome, thanks again for catching this issue. The app can only render the UI components once time extent info of GLDAS layers are ready (see this [line](https://github.com/Esri/water-balance-app/blob/master/src/components/App/App.tsx#L128) here), since the old GLDAS services were retired, it won't be able to provide the time extent info either, which caused the issue you saw.
